# For more info on HTTP files go to https://aka.ms/vs/httpfile

@url=https://localhost:7119
@token=CfDJ8F1wTwxgthNHnEqQW0YAn3AIKYWHhZ2yZY4Ih31aTLJI1KXbGQo2VzrRcicSQvP72MbgzuywOzMaUH1gUBueK01DT8nz51E9c_gPxWP2m4lTKVewVM0ajtfsfEmtDHIjf9Qr9RpIafzi1hg9wboBODvg7V2a3KwFknUsfrjAo98G8-V9348hhNFyywh5PpGbOI2rVDzllHOSYBe9RxPkN0cMIS7aEKb5v7_kZ3BOAgjuxeE3K2PHXaVfUVwJl40uyxvfQTw2M-_-xYqB7oQLJRFHm15pOXv490l4qs21FmIn_nrgDZkPAYCKPVjeQVVic4FQOafekUlnJGpj61ToOhVVpneozKZ2PlwAJ2tRCqM84b6KvEMgutiiOsAnrOIv0sciESd1yIVysnnDrrGS-voA2lrRLqBgOKYBibmtFZNSLOpNXbi_mF_KBw7tNzoVqNQP_4sngvYqvZFws8tDfy3m8liyiskkhUviAsfiW8Yh8pNv1Z0uXYGwshmR9tmcD4m480Dr_cB6FwNO7ulDFZ7h4vtpPdC5nTjjJprpft-f6GsSU2e1Olf_4ZMUTzKM4m4V63RuR_U6QvEwBsqQTu0captIlTwghplS_DYcZVK65iDUi-I7NjLnife8-hHzQW7EDhNAYvX_hizDohk1n1gL8njHz36KATz3LJ73Q7TdCyfrfW7kd5WAXlx0P20HQg

# Register new portal
POST {{url}}/api/portals
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "name": "Test3",
    "maxInstanceCount": 1,
    "vpnType": "OpenVPN",
    "vpnConfig": "Empty"
}
###

# Get portals
GET {{url}}/api/portals?}
Authorization: Bearer {{token}}
Accept: application/json
###


@portalId=4de273c6-0b9c-4e5a-8c0d-9ca7f55666e9
# Get portal
GET {{url}}/api/portals/{{portalId}}
Authorization: Bearer {{token}}
Accept: application/json
###

# Delete portal
DELETE {{url}}/api/portals/{{portalId}}
Authorization: Bearer {{token}}

###

# Update portal
PUT {{url}}/api/portals/{{portalId}}
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "name": "Test3-1",
    "maxInstanceCount": 2,
    "vpnType": "None",
    "vpnConfig": "null"
}
###

# Patch portal
# https://datatracker.ietf.org/doc/html/rfc6902
PATCH {{url}}/api/portals/{{portalId}}
Content-Type: application/json

[
    {
        "op": "replace",
        "path": "/name",
        "value": "Test3-1"
    },
    {
        "op": "replace",
        "path": "/maxInstanceCount",
        "value": 3
    }
]

###

